//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManager.Data
{
    using System.Data.Entity;
    
    public partial class EmployeesEntities : DbContext
    {
        /// <summary>
        ///     Constructs a new instance of
        ///     <see cref="T:EmployeeManager.Data.EmployeesEntities" /> and returns a
        ///     reference to it.
        /// </summary>
        /// <param name="connectionString">
        ///     (Required.) String containing either the
        ///     configuration file entry name or actual data source connection string to
        ///     utilize in order to access the entities.
        /// </param>
        public EmployeesEntities(string connectionString = "name=EmployeesEntities")
            : base(connectionString)
        {
        }  /* constructor closing brace */
    
#region Datasets
    /// <summary>
    ///     Gets a <see cref="T:System.Data.Entity.DbSet{EmployeeManager.Data.Employee}" />
    ///     containing the database objects for the Employees table.
    /// </summary>
    public virtual DbSet<Employee> Employees { get; set; }
    
    /// <summary>
    ///     Gets a <see cref="T:System.Data.Entity.DbSet{EmployeeManager.Data.EmployeeType}" />
    ///     containing the database objects for the EmployeeTypes table.
    /// </summary>
    public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
    
#endregion    
    
    }
}
