//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EmployeeManager.Data;

namespace EmployeeManager.BusinessLayer
{
    /// <summary>
    /// Provides access to data from the Employees table in the data source.
    /// </summary>
    public partial interface IEmployeeRepository : IEmployeesRepository<Employee>
    {
        // TODO: Add any additional repository methods other than the generic ones (GetAll, GetById, Delete, Add).
    }
}
