//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string App_IdleMessage {
            get {
                return ResourceManager.GetString("App_IdleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} row(s) affected..
        /// </summary>
        internal static string App_NonzeroRowsAffectedFormat {
            get {
                return ResourceManager.GetString("App_NonzeroRowsAffectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes....
        /// </summary>
        internal static string App_SavingChangesMessage {
            get {
                return ResourceManager.GetString("App_SavingChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes to the system....
        /// </summary>
        internal static string App_SavingChangesProgressWindowMessage {
            get {
                return ResourceManager.GetString("App_SavingChangesProgressWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No row(s) affected..
        /// </summary>
        internal static string App_ZeroRowsAffected {
            get {
                return ResourceManager.GetString("App_ZeroRowsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Type.
        /// </summary>
        internal static string ColumnHeader_EmployeeType {
            get {
                return ResourceManager.GetString("ColumnHeader_EmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string Confirm_DeleteEmployee {
            get {
                return ResourceManager.GetString("Confirm_DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the data has been updated.
        ///
        ///Do you want to save your changes before exiting?.
        /// </summary>
        internal static string Confirm_SaveChangesOnExit {
            get {
                return ResourceManager.GetString("Confirm_SaveChangesOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot find the database on the system.
        ///
        ///Please put the Employees.mdf file in the same folder as EmployeeManager.exe, and then try again..
        /// </summary>
        internal static string Error_CannotFindDatabase {
            get {
                return ResourceManager.GetString("Error_CannotFindDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Employee Type for {0}..
        /// </summary>
        internal static string Error_SelectionOfEmployeeTypeRequired {
            get {
                return ResourceManager.GetString("Error_SelectionOfEmployeeTypeRequired", resourceCulture);
            }
        }
    }
}
